// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComentario = "comentario"

// Comentario mapped from table <comentario>
type Comentario struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UsuarioID int32     `gorm:"column:usuario_id;not null" json:"usuario_id"`
	Fecha     time.Time `gorm:"column:fecha;not null" json:"fecha"`
	Tema      string    `gorm:"column:tema;not null" json:"tema"`
	Mensaje   string    `gorm:"column:mensaje;not null" json:"mensaje"`
	TemaID    int32     `gorm:"column:tema_id;not null" json:"tema_id"`
}

// TableName Comentario's table name
func (*Comentario) TableName() string {
	return TableNameComentario
}
