// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/Fonzeca/Chatline/src/db/model"
)

func newComentario(db *gorm.DB) comentario {
	_comentario := comentario{}

	_comentario.comentarioDo.UseDB(db)
	_comentario.comentarioDo.UseModel(&model.Comentario{})

	tableName := _comentario.comentarioDo.TableName()
	_comentario.ALL = field.NewAsterisk(tableName)
	_comentario.ID = field.NewInt32(tableName, "id")
	_comentario.UsuarioID = field.NewInt32(tableName, "usuario_id")
	_comentario.Usuario = field.NewString(tableName, "usuario")
	_comentario.Fecha = field.NewTime(tableName, "fecha")
	_comentario.Tema = field.NewString(tableName, "tema")
	_comentario.Mensaje = field.NewString(tableName, "mensaje")
	_comentario.TemaID = field.NewInt32(tableName, "tema_id")

	_comentario.fillFieldMap()

	return _comentario
}

type comentario struct {
	comentarioDo

	ALL       field.Asterisk
	ID        field.Int32
	UsuarioID field.Int32
	Usuario   field.String
	Fecha     field.Time
	Tema      field.String
	Mensaje   field.String
	TemaID    field.Int32

	fieldMap map[string]field.Expr
}

func (c comentario) Table(newTableName string) *comentario {
	c.comentarioDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c comentario) As(alias string) *comentario {
	c.comentarioDo.DO = *(c.comentarioDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *comentario) updateTableName(table string) *comentario {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt32(table, "id")
	c.UsuarioID = field.NewInt32(table, "usuario_id")
	c.Usuario = field.NewString(table, "usuario")
	c.Fecha = field.NewTime(table, "fecha")
	c.Tema = field.NewString(table, "tema")
	c.Mensaje = field.NewString(table, "mensaje")
	c.TemaID = field.NewInt32(table, "tema_id")

	c.fillFieldMap()

	return c
}

func (c *comentario) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *comentario) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 7)
	c.fieldMap["id"] = c.ID
	c.fieldMap["usuario_id"] = c.UsuarioID
	c.fieldMap["usuario"] = c.Usuario
	c.fieldMap["fecha"] = c.Fecha
	c.fieldMap["tema"] = c.Tema
	c.fieldMap["mensaje"] = c.Mensaje
	c.fieldMap["tema_id"] = c.TemaID
}

func (c comentario) clone(db *gorm.DB) comentario {
	c.comentarioDo.ReplaceDB(db)
	return c
}

type comentarioDo struct{ gen.DO }

func (c comentarioDo) Debug() *comentarioDo {
	return c.withDO(c.DO.Debug())
}

func (c comentarioDo) WithContext(ctx context.Context) *comentarioDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c comentarioDo) ReadDB() *comentarioDo {
	return c.Clauses(dbresolver.Read)
}

func (c comentarioDo) WriteDB() *comentarioDo {
	return c.Clauses(dbresolver.Write)
}

func (c comentarioDo) Clauses(conds ...clause.Expression) *comentarioDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c comentarioDo) Returning(value interface{}, columns ...string) *comentarioDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c comentarioDo) Not(conds ...gen.Condition) *comentarioDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c comentarioDo) Or(conds ...gen.Condition) *comentarioDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c comentarioDo) Select(conds ...field.Expr) *comentarioDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c comentarioDo) Where(conds ...gen.Condition) *comentarioDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c comentarioDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *comentarioDo {
	return c.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (c comentarioDo) Order(conds ...field.Expr) *comentarioDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c comentarioDo) Distinct(cols ...field.Expr) *comentarioDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c comentarioDo) Omit(cols ...field.Expr) *comentarioDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c comentarioDo) Join(table schema.Tabler, on ...field.Expr) *comentarioDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c comentarioDo) LeftJoin(table schema.Tabler, on ...field.Expr) *comentarioDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c comentarioDo) RightJoin(table schema.Tabler, on ...field.Expr) *comentarioDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c comentarioDo) Group(cols ...field.Expr) *comentarioDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c comentarioDo) Having(conds ...gen.Condition) *comentarioDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c comentarioDo) Limit(limit int) *comentarioDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c comentarioDo) Offset(offset int) *comentarioDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c comentarioDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *comentarioDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c comentarioDo) Unscoped() *comentarioDo {
	return c.withDO(c.DO.Unscoped())
}

func (c comentarioDo) Create(values ...*model.Comentario) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c comentarioDo) CreateInBatches(values []*model.Comentario, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c comentarioDo) Save(values ...*model.Comentario) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c comentarioDo) First() (*model.Comentario, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Comentario), nil
	}
}

func (c comentarioDo) Take() (*model.Comentario, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Comentario), nil
	}
}

func (c comentarioDo) Last() (*model.Comentario, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Comentario), nil
	}
}

func (c comentarioDo) Find() ([]*model.Comentario, error) {
	result, err := c.DO.Find()
	return result.([]*model.Comentario), err
}

func (c comentarioDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Comentario, err error) {
	buf := make([]*model.Comentario, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c comentarioDo) FindInBatches(result *[]*model.Comentario, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c comentarioDo) Attrs(attrs ...field.AssignExpr) *comentarioDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c comentarioDo) Assign(attrs ...field.AssignExpr) *comentarioDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c comentarioDo) Joins(fields ...field.RelationField) *comentarioDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c comentarioDo) Preload(fields ...field.RelationField) *comentarioDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c comentarioDo) FirstOrInit() (*model.Comentario, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Comentario), nil
	}
}

func (c comentarioDo) FirstOrCreate() (*model.Comentario, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Comentario), nil
	}
}

func (c comentarioDo) FindByPage(offset int, limit int) (result []*model.Comentario, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c comentarioDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c comentarioDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c comentarioDo) Delete(models ...*model.Comentario) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *comentarioDo) withDO(do gen.Dao) *comentarioDo {
	c.DO = *do.(*gen.DO)
	return c
}
